# Generated by Django 5.2.8 on 2025-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('self_help', 'Self-Help'), ('romance', 'Romance'), ('trading_finance', 'Trading & Finance'), ('hindi', 'Hindi Books'), ('kids', 'Kids Books'), ('manga', 'Manga'), ('mythology', 'Mythology'), ('science', 'Science'), ('biography', 'Biography & Autobiography'), ('robert_greene_special', 'Robert Greene Special'), ('preloved_bestsellers', 'Preloved Bestsellers'), ('new_arrivals', 'New Arrivals')], default='self_help', max_length=50),
        ),
    ]
